# H2 in memory
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate DDL auto (create schemas on startup)
spring.jpa.hibernate.ddl-auto=update

# Shows SQL in console
spring.jpa.show-sql=true

# Web console of H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
